on:
  release:
    types:
    - published
name: Build Release
jobs:
  release-assests:
    name: release kubectl-karmada
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --skip-publish --skip-validate --rm-dist
    - name: Uploading assets...
      if: ${{ !env.ACT }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/kubectl-karmada-darwin-amd64.tar.gz
          ./bin/kubectl-karmada-darwin-arm64.tar.gz
          ./bin/kubectl-karmada-linux-amd64.tar.gz
          ./bin/kubectl-karmada-linux-arm64.tar.gz
          ./bin/checksums.txt
          ./crds.tar.gz
  update-krew-index:
    needs: release-assests
    name: Update krew-index
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.40
